[package]
name = "rust_test_case"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 3

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
rust-embed = "8.8.0"
image = "0.25.8"
opencv = "0.96.0"
screenshots = "0.8.0"
chrono = { version = "0.4", features = ["serde"] }
