[package]
name = "rust_test_case"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
tokio-util = "0.7"
futures = "0.3"
rand = "0.8"
num_cpus = "1.0"
rust-embed = "8.7.2"
image = "0.25.8"
opencv = "0.86"
win-screenshot = "0.1"
