[package]
name = "rust_test_case"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 3

[dependencies]
tokio = { version = "1.0", features = ["full"] }
rust-embed = "8.7.2"
image = "0.25.8"
opencv = "0.96.0"
